name: mocktester
description: "MockTester - Premier CBT Mock Test App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  device_info_plus: ^11.1.0
  shared_preferences: ^2.3.2
  flutter_math_fork: ^0.7.2
  file_picker: ^8.1.2
  pdf: ^3.11.1
  printing: ^5.13.1
  image_picker: ^1.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  firebase_in_app_messaging: ^0.8.0+4
  google_sign_in: ^6.2.1
  sqflite: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  archive: ^4.0.2
  supabase_flutter: ^2.6.0
  llama_cpp_dart: ^0.1.72

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/data/database/bpsc_database.db.gz
