const Map<String, List<String>> kBiharDistrictCityMap = {
  'Patna': [
    'Musallahpur Hat',
    'Boring Road',
    'Kankarbagh',
    'Bazar Samiti',
    'Ashok Rajpath',
    'Rajendra Nagar',
    'Danapur',
    'Khagaul',
    'Barh',
    'Mokama',
    'Fatuha',
    'Bakhtiyarpur',
    'Bihta',
    'Paliganj',
    'Other / Rural Area',
  ],
  'Gaya': [
    'Gaya Main City',
    'Bodhan Road',
    'AP Colony',
    'Bodh Gaya',
    'Sherghati',
    'Tekari',
    'Manpur',
    'Imamganj',
    'Other / Rural Area',
  ],
  'Muzaffarpur': [
    'Zero Mile',
    'Mithanpura',
    'Aghoria Bazar',
    'Brahmpura',
    'Kanti',
    'Motipur',
    'Sahebganj',
    'Sakra',
    'Other / Rural Area',
  ],
  'Bhagalpur': [
    'Bhagalpur City',
    'Tilkamanjhi',
    'Naugachia',
    'Kahalgaon',
    'Sabour',
    'Sultanganj',
    'Other / Rural Area',
  ],
  'Bhojpur (Ara)': [
    'Ara Town',
    'Nawada (Ara)',
    'Jagdishpur',
    'Piro',
    'Shahpur',
    'Koilwar',
    'Bihiya',
    'Other / Rural Area',
  ],
  'Darbhanga': [
    'Darbhanga Town',
    'Laheriasarai',
    'Benipur',
    'Baheri',
    'Biraul',
    'Jale',
    'Other / Rural Area',
  ],
  'Nalanda (Bihar Sharif)': [
    'Bihar Sharif Town',
    'Rajgir',
    'Hilsa',
    'Islampur',
    'Pawapuri',
    'Silao',
    'Other / Rural Area',
  ],
  'Purnia': [
    'Purnia Town',
    'Bhatta Bazar',
    'Line Bazar',
    'Banmankhi',
    'Kasba',
    'Dhamdaha',
    'Rupauli',
    'Other / Rural Area',
  ],
  'Rohtas (Sasaram)': [
    'Sasaram Town',
    'Dehri-on-Sone',
    'Bikramganj',
    'Nokha',
    'Chenari',
    'Other / Rural Area',
  ],
  'Saran (Chhapra)': [
    'Chhapra Town',
    'Sonpur',
    'Marhaura',
    'Ekma',
    'Revelganj',
    'Other / Rural Area',
  ],
  'Begusarai': [
    'Begusarai Town',
    'Barauni',
    'Teghra',
    'Bakhri',
    'Ballia',
    'Manjhaul',
    'Other / Rural Area',
  ],
  'Vaishali (Hajipur)': [
    'Hajipur Town',
    'Lalganj',
    'Mahuwa',
    'Jandaha',
    'Vaishali',
    'Patepur',
    'Other / Rural Area',
  ],
  'East Champaran (Motihari)': [
    'Motihari Town',
    'Raxaul',
    'Chakia',
    'Dhaka',
    'Areraj',
    'Pakridayal',
    'Other / Rural Area',
  ],
  'West Champaran (Bettiah)': [
    'Bettiah Town',
    'Bagaha',
    'Narkatiaganj',
    'Ramnagar',
    'Chanpatia',
    'Other / Rural Area',
  ],
  'Samastipur': [
    'Samastipur Town',
    'Dalsinghsarai',
    'Rosera',
    'Patori',
    'Kalyanpur',
    'Tajpur',
    'Other / Rural Area',
  ],
  'Siwan': [
    'Siwan Town',
    'Maharajganj',
    'Mairwa',
    'Goreakothi',
    'Raghunathpur',
    'Other / Rural Area',
  ],
  'Madhubani': [
    'Madhubani Town',
    'Jhanjharpur',
    'Benipatti',
    'Jayanagar',
    'Phulparas',
    'Other / Rural Area',
  ],
  'Katihar': [
    'Katihar Town',
    'Barsoi',
    'Manihari',
    'Korha',
    'Other / Rural Area',
  ],
  'Saharsa': [
    'Saharsa Town',
    'Simri Bakhtiarpur',
    'Saur Bazar',
    'Kahra',
    'Other / Rural Area',
  ],
  'Munger': [
    'Munger Town',
    'Jamalpur',
    'Kharagpur',
    'Tarapur',
    'Other / Rural Area',
  ],
  'Buxar': [
    'Buxar Town',
    'Dumraon',
    'Itarhi',
    'Brahmpur',
    'Other / Rural Area',
  ],
  'Gopalganj': [
    'Gopalganj Town',
    'Hathwa',
    'Mirganj',
    'Barauli',
    'Other / Rural Area',
  ],
  'Aurangabad': [
    'Aurangabad Town',
    'Daudnagar',
    'Rafiganj',
    'Obra',
    'Other / Rural Area',
  ],
  'Jehanabad': [
    'Jehanabad Town',
    'Makhdumpur',
    'Kako',
    'Ghoshi',
    'Other / Rural Area',
  ],
  'Nawada': [
    'Nawada Town',
    'Rajauli',
    'Hisua',
    'Warsaliganj',
    'Other / Rural Area',
  ],
  'Sitamarhi': [
    'Sitamarhi Town',
    'Bairgania',
    'Pupri',
    'Dumra',
    'Sursand',
    'Other / Rural Area',
  ],
  'Supaul': [
    'Supaul Town',
    'Birpur',
    'Triveniganj',
    'Nirmali',
    'Other / Rural Area',
  ],
  'Khagaria': [
    'Khagaria Town',
    'Gogri Jamalpur',
    'Parbatta',
    'Beldaur',
    'Other / Rural Area',
  ],
  'Jamui': [
    'Jamui Town',
    'Jhajha',
    'Sono',
    'Chakai',
    'Other / Rural Area',
  ],
  'Araria': [
    'Araria Town',
    'Forbesganj',
    'Raniganj',
    'Jokihat',
    'Other / Rural Area',
  ],
  'Kishanganj': [
    'Kishanganj Town',
    'Bahadurganj',
    'Thakurganj',
    'Pothia',
    'Other / Rural Area',
  ],
  'Lakhisarai': [
    'Lakhisarai Town',
    'Barahiya',
    'Surajgarha',
    'Pipariya',
    'Other / Rural Area',
  ],
  'Madhepura': [
    'Madhepura Town',
    'Singheshwar',
    'Murliganj',
    'Alamnagar',
    'Other / Rural Area',
  ],
  'Banka': [
    'Banka Town',
    'Amarpur',
    'Katoria',
    'Belhar',
    'Other / Rural Area',
  ],
  'Kaimur (Bhabua)': [
    'Bhabua Town',
    'Mohania',
    'Ramgarh',
    'Chainpur',
    'Other / Rural Area',
  ],
  'Arwal': [
    'Arwal Town',
    'Kurtha',
    'Kaler',
    'Sonbhadra',
    'Other / Rural Area',
  ],
  'Sheikhpura': [
    'Sheikhpura Town',
    'Barbigha',
    'Ariari',
    'Chewara',
    'Other / Rural Area',
  ],
  'Sheohar': [
    'Sheohar Town',
    'Dumri Katsari',
    'Tariyani',
    'Piprarhi',
    'Other / Rural Area',
  ],
};
